-- Criar tabela subscribers
CREATE TABLE subscribers (
   id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name VARCHAR2(100) NOT NULL,
   email VARCHAR2(255) NOT NULL UNIQUE,
   gender VARCHAR2(10),
   created_at DATE DEFAULT SYSDATE,
   updated_at DATE DEFAULT SYSDATE
);

-- Trigger para atualizar updated_at automaticamente
CREATE OR REPLACE TRIGGER trg_subscribers_updated_at
    BEFORE UPDATE ON subscribers
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSDATE;
END;
